<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Title>WoW2.Sdk.Language.Serialization.Json.Abstractions</Title>
        <PackageId>WoW2.Sdk.Language.Serialization.Json.Abstractions</PackageId>
        <Description>Abstractions for JSON serialization in the WoW2 SDK</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>serialization, json, abstractions</PackageTags>
        <Version>9.0.0-alpha.1</Version>
        <Authors>WoW 2.0 Team</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/wow-two-sdk/sdk.language.serialization</PackageProjectUrl>
        <RepositoryUrl>https://github.com/wow-two-sdk/sdk.language.serialization</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageIcon>wow2.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="wow2.png" Pack="true" PackagePath=""/>
        <None Include="README.md" Pack="true" PackagePath=""/>
    </ItemGroup>

</Project>